# Generated by Django 5.2 on 2025-04-09 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villes', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('collaborateurs', models.TextField()),
                ('interimaire', models.IntegerField()),
                ('heures', models.IntegerField()),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ettec.chantier')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ettec.employee')),
            ],
        ),
        migrations.AddField(
            model_name='chantier',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ettec.zones'),
        ),
    ]
