# Generated by Django 5.2 on 2025-04-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presences',
            new_name='Presence',
        ),
        migrations.RenameModel(
            old_name='Zones',
            new_name='Zone',
        ),
    ]
