# Generated by Django 5.2 on 2025-04-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0002_rename_presences_presence_rename_zones_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='chantier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ettec.chantier'),
        ),
    ]
