# Generated by Django 5.2 on 2025-04-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0003_alter_presence_chantier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('date', models.DateField()),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ettec.chantier')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ettec.employee')),
            ],
        ),
    ]
