# Generated by Django 5.2 on 2025-04-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0004_photochantier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='collaborateurs',
        ),
        migrations.AddField(
            model_name='presence',
            name='collaborateurs',
            field=models.ManyToManyField(blank=True, related_name='presences_collaborateur', to='Ettec.employee'),
        ),
    ]
