# Generated by Django 5.2 on 2025-04-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0005_remove_presence_collaborateurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photochantier',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
