# Generated by Django 5.2 on 2025-04-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0006_alter_photochantier_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('name', models.CharField(max_length=100)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ettec.chantier')),
            ],
        ),
    ]
