# Generated by Django 5.2 on 2025-04-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0009_employee_groups_employee_is_active_employee_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
