# Generated by Django 5.2 on 2025-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0010_employee_email_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
