# Generated by Django 5.2 on 2025-04-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0012_formations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formations',
            new_name='Formation',
        ),
    ]
