# Generated by Django 5.2 on 2025-04-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0013_rename_formations_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='formations',
            field=models.ManyToManyField(blank=True, to='Ettec.formation'),
        ),
    ]
