# Generated by Django 5.2 on 2025-04-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0014_employee_formations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='btp_card',
            field=models.ImageField(blank=True, null=True, upload_to='btp_cards/'),
        ),
    ]
