# Generated by Django 5.2 on 2025-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0015_employee_btp_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contrat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
