# Generated by Django 5.2 on 2025-04-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0016_employee_contrat_employee_lastname_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='heures',
            field=models.FloatField(),
        ),
    ]
