# Generated by Django 5.2 on 2025-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0018_alter_employee_formations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='formations',
            field=models.ManyToManyField(blank=True, to='Ettec.formation'),
        ),
    ]
