# Generated by Django 5.2 on 2025-05-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0019_alter_employee_formations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
