# Generated by Django 5.2 on 2025-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0020_employee_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raccourcis', models.CharField(max_length=10)),
            ],
        ),
    ]
