# Generated by Django 5.2 on 2025-05-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ettec', '0021_statustravail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photochantier',
            name='has_been_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
